#define T_DATA_DIRECTIVE	10
#define T_BYTE_DIRECTIVE	11
#define T_HALF_DIRECTIVE	12
#define T_WORD_DIRECTIVE	13
#define	T_ASCII_DIRECTIVE	14
#define T_ASCIIZ_DIRECTIVE	15
#define T_FLOAT_DIRECTIVE	16
#define	T_DOUBLE_DIRECTIVE	17
#define	T_SPACE_DIRECTIVE	18
#define	T_TEXT_DIRECTIVE	19
#define T_GLOBL_DIRECTIVE	20
#define	T_ENT_DIRECTIVE		21
#define	T_END_DIRECTIVE		22
#define	T_COLON			23
#define T_LB			24
#define T_RB			25
#define T_COMMA			26
#define T_LOAD_BYTE		27
#define T_LOAD_HALF_WORD	28
#define T_LOAD_WORD		29
#define T_LOAD_IMMEDIATE	30
#define T_LOAD_ADDR		31
#define T_STORE_BYTE		32
#define T_STORE_HALF_WORD	33
#define T_STORE_WORD		34
#define T_ADD			35
#define T_ADDU			36
#define T_SUB			37
#define T_SUBU			38
#define T_SYSCALL		39
#define T_JUMP			40

#define T_REG			41
#define T_INT_NUM		42
#define T_ID			43
#define T_LITERALL		44
#define T_END_VAL		45
